name: oaprmr
channels:
  - defaults
  - pytorch-lts
  - nvidia
  - simpleitk
  - conda-forge
dependencies:
  - python=3.8.8
  - joblib
  - cython
  - numpy
  - numba
  - scipy
  - pandas
  - scikit-image
  - scikit-learn
  - pywavelets
  - scikit-learn
  - matplotlib
  - seaborn
  - opencv
  - jupyter
  - xlrd
  - pyreadstat
  - pytorch=1.8.2
  - torchvision
  - captum=0.4.0
  - cudatoolkit=11.1
  - cudatoolkit-dev=11.1
  - tensorboard
  - tensorflow
  - simpleitk
  - pip
  - pip:
    - pydicom
    - dicom2nifti
    - tifffile
    - sas7bdat
    - nibabel
    - tqdm
    - pretrainedmodels
    - hydra-core
    - einops
    - torchsummary
    - iterative-stratification
    - opencv-python
    - thop
